import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { UserProvider } from "@/components/UserProvider";
import { MessageCircle } from "lucide-react";
import NavLinks from "@/components/NavLinks";
import BrandLink from "@/components/BrandLink";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Onboarding AI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <UserProvider>
          <header className="border-b border-zinc-200 dark:border-zinc-800 bg-white dark:bg-black">
            <div className="mx-auto max-w-6xl px-4 py-3 flex items-center justify-between">
              <BrandLink />
              <NavLinks />
            </div>
          </header>
          <main className="mx-auto max-w-6xl px-4">
            {children}
          </main>
        </UserProvider>
        <a
          href="/qa"
          aria-label="Open Knowledge Base Chat"
          className="fixed bottom-6 right-6 z-50 inline-flex items-center justify-center h-12 w-12 rounded-full bg-purple-600 text-white shadow-lg hover:bg-purple-700 focus:outline-none focus:ring-2 focus:ring-purple-400"
          title="Chat"
        >
          <MessageCircle className="h-6 w-6" aria-hidden />
        </a>
      </body>
    </html>
  );
}
